// Enrolled atelier phones — the identity layer of the atelier PWA.
//
// The legacy Android app identified a régleur by his phone: `NomAppareil()`
// (the ANDROID_ID) matched against a hard-coded list — « Terminal Nico »,
// « Terminal Mickaël ». The web cannot read a hardware id, so a phone's
// identity is a secret ISSUED BY THIS SERVER at enrolment and carried back in
// its own cookie (`mps_appareil`, lib/auth.ts). Design: ~/.claude/plans/
// atelier-malterre.md §3.2–3.4.
//
// One row per phone:
//   - `IDutilisateur` — the account the phone acts as. Being enrolled is what
//     lets the phone record production: no separate grant on this account
//     (the `saisie_atelier` key was removed on 2026-09-15 — an admin issues
//     every enrolment code, so an enrolled phone is by definition allowed).
//     A régleur's phone is enrolled under his personal account; a shared
//     bonnetier phone under the atelier station account.
//   - `IDbonnetier` — a FIXED identity (a régleur's phone): the app opens as
//     him, with the régleur screens, no face grid, and the API refuses any
//     write naming someone else. `null` = a shared phone: the face grid of
//     non-régleurs, who did the work travels in the body as the legacy does.
//
// The cookie payload is `<id>.<secret>`; only sha256(secret) is stored, so the
// file on disk cannot be turned into a cookie, and revoking = deleting the row
// (the plan's requirement: a copied cookie must be killable without rotating
// AUTH_COOKIE_SECRET, which would log every ETM and TRM user out).
//
// Enrolment is a one-time 6-digit code generated by an admin in Paramètres ›
// Utilisateurs (10 min, single use, kept in memory — an API restart simply
// voids pending codes). The phone types it once.
//
// Storage: `data/appareils-atelier.json` next to permissions-trm.json.
// ⚠️ NOT the module-load cache of lib/permissions-trm.ts (which once wiped 10
// `edit_of` grants when a script and the API both wrote the file): this store
// re-reads when the file's mtime moved and serialises its own writes.

import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import crypto from 'node:crypto'
import { fileURLToPath } from 'node:url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const DATA_DIR = path.resolve(__dirname, '../../data')
const FILE_PATH = path.join(DATA_DIR, 'appareils-atelier.json')

/** What an enrolled device is for. The store also holds the POINTEUSE tablet
 *  (routes/pointage.ts, 2026-09-15): one list in Paramètres › Utilisateurs ›
 *  Appareils, one revocation. A code enrols only its own type, and each app
 *  refuses the other's devices — a tablet never records production, a phone
 *  never clocks anyone in. Rows written before the type existed are phones. */
export type AppareilType = 'atelier' | 'pointeuse'

export function typeAppareil(a: { type?: AppareilType }): AppareilType {
  return a.type ?? 'atelier'
}

export interface AppareilAtelier {
  id: number
  /** Absent on rows enrolled before 2026-09-15 = 'atelier'. Read through typeAppareil(). */
  type?: AppareilType
  /** sha256 (hex) of the bearer secret carried by the cookie. */
  secretHash: string
  /** The account the phone acts as (its TRM grants apply). */
  IDutilisateur: number
  /** Fixed identity (a régleur's own phone), or null for a shared phone. */
  IDbonnetier: number | null
  /** Human label, e.g. « Téléphone Nico » — also stamped on
   *  `evenement_piece.appareil`, where the legacy wrote its terminal name. */
  libelle: string
  /** ISO timestamps. */
  creeLe: string
  /** IDutilisateur of the admin who generated the code. */
  creePar: number
  vuLe: string | null
}

/** What the API exposes about a phone — never the hash. */
export type AppareilPublic = Omit<AppareilAtelier, 'secretHash'>

interface AppareilsFile {
  version: 1
  appareils: AppareilAtelier[]
}

export const LIBELLE_MAX = 50
export const CODE_TTL_MS = 10 * 60_000
/** `vuLe` is refreshed at most this often per phone, so a polling PWA does
 *  not turn into a disk write every 10 s. */
const VU_THROTTLE_MS = 10 * 60_000

// ── File store (mtime-invalidated cache, serialised writes) ───────────────

let cache: { file: AppareilsFile; mtimeMs: number } | null = null
let writeChain: Promise<void> = Promise.resolve()

function emptyFile(): AppareilsFile {
  return { version: 1, appareils: [] }
}

async function load(): Promise<AppareilsFile> {
  let mtimeMs: number
  try {
    mtimeMs = (await fs.stat(FILE_PATH)).mtimeMs
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') {
      cache = { file: emptyFile(), mtimeMs: 0 }
      return cache.file
    }
    throw err
  }
  if (cache && cache.mtimeMs === mtimeMs) return cache.file
  const raw = await fs.readFile(FILE_PATH, 'utf8')
  const parsed = JSON.parse(raw) as AppareilsFile
  if (!parsed || parsed.version !== 1 || !Array.isArray(parsed.appareils)) {
    throw new Error('appareils-atelier.json: invalid shape')
  }
  cache = { file: parsed, mtimeMs }
  return parsed
}

/** Every write goes through here, one at a time: read the file fresh, apply,
 *  write atomically (tmp + rename). `mutate` returns what the caller wants. */
function ecrire<T>(mutate: (file: AppareilsFile) => T): Promise<T> {
  const run = async (): Promise<T> => {
    const file = await load()
    const next: AppareilsFile = { version: 1, appareils: file.appareils.map((a) => ({ ...a })) }
    const out = mutate(next)
    await fs.mkdir(DATA_DIR, { recursive: true })
    const tmp = `${FILE_PATH}.tmp`
    await fs.writeFile(tmp, JSON.stringify(next, null, 2), 'utf8')
    await fs.rename(tmp, FILE_PATH)
    cache = { file: next, mtimeMs: (await fs.stat(FILE_PATH)).mtimeMs }
    return out
  }
  const p = writeChain.then(run, run)
  writeChain = p.then(
    () => undefined,
    () => undefined,
  )
  return p
}

export function publier(a: AppareilAtelier): AppareilPublic {
  const { secretHash: _h, ...rest } = a
  return rest
}

export async function listerAppareils(): Promise<AppareilPublic[]> {
  return (await load()).appareils.map(publier)
}

// ── Cookie token ───────────────────────────────────────────────────────────

function hashSecret(secret: string): string {
  return crypto.createHash('sha256').update(secret).digest('hex')
}

/** Parse `<id>.<secret>`; null when malformed. Pure, exported for tests. */
export function parseToken(raw: string | undefined | null): { id: number; secret: string } | null {
  if (!raw || typeof raw !== 'string') return null
  const dot = raw.indexOf('.')
  if (dot < 1) return null
  const idPart = raw.slice(0, dot)
  const secret = raw.slice(dot + 1)
  if (!/^\d{1,9}$/.test(idPart) || !/^[A-Za-z0-9_-]{20,}$/.test(secret)) return null
  return { id: parseInt(idPart, 10), secret }
}

/** Constant-time check of a presented secret against a stored hash. Pure. */
export function secretMatches(secret: string, secretHash: string): boolean {
  const a = Buffer.from(hashSecret(secret), 'hex')
  const b = Buffer.from(secretHash, 'hex')
  return a.length === b.length && crypto.timingSafeEqual(a, b)
}

/** Resolve a cookie value to its enrolled phone, or null (unknown, revoked,
 *  tampered). Refreshes `vuLe` (throttled) as a side effect. */
export async function resoudreAppareil(raw: string | undefined | null): Promise<AppareilAtelier | null> {
  const tok = parseToken(raw)
  if (!tok) return null
  const file = await load()
  const a = file.appareils.find((x) => x.id === tok.id)
  if (!a || !secretMatches(tok.secret, a.secretHash)) return null
  const now = Date.now()
  if (!a.vuLe || now - Date.parse(a.vuLe) > VU_THROTTLE_MS) {
    const vuLe = new Date(now).toISOString()
    a.vuLe = vuLe // optimistic, so a burst of requests writes once
    void ecrire((f) => {
      const row = f.appareils.find((x) => x.id === tok.id)
      if (row) row.vuLe = vuLe
    }).catch((err) => console.error('appareils-atelier: vuLe write failed', err))
  }
  return a
}

// ── Enrolment codes (in memory) ────────────────────────────────────────────

export interface CodeEnrolement {
  code: string
  type: AppareilType
  IDutilisateur: number
  IDbonnetier: number | null
  libelle: string
  creePar: number
  /** ms epoch */
  expireLe: number
}

const codes = new Map<string, CodeEnrolement>()

function purgerCodes(now: number): void {
  for (const [k, c] of codes) if (c.expireLe <= now) codes.delete(k)
}

export function listerCodes(now = Date.now()): CodeEnrolement[] {
  purgerCodes(now)
  return [...codes.values()].sort((a, b) => a.expireLe - b.expireLe)
}

/** Six digits, unique among the pending codes. */
export function creerCode(
  input: { type?: AppareilType; IDutilisateur: number; IDbonnetier: number | null; libelle: string; creePar: number },
  now = Date.now(),
): CodeEnrolement {
  purgerCodes(now)
  let code: string
  do {
    code = String(crypto.randomInt(0, 1_000_000)).padStart(6, '0')
  } while (codes.has(code))
  const entry: CodeEnrolement = {
    code,
    type: input.type ?? 'atelier',
    IDutilisateur: input.IDutilisateur,
    IDbonnetier: input.IDbonnetier,
    libelle: input.libelle,
    creePar: input.creePar,
    expireLe: now + CODE_TTL_MS,
  }
  codes.set(code, entry)
  return entry
}

/** Whether an admin has a code pending FOR THIS TYPE of device — the ONE fact
 *  about codes a device that is not enrolled may learn (the PWA only offers
 *  « Enrôler » while there is something to type). Never the code itself. */
export function codeEnAttente(now = Date.now(), type: AppareilType = 'atelier'): boolean {
  return listerCodes(now).some((c) => c.type === type)
}

export function annulerCode(code: string): boolean {
  return codes.delete(code)
}

/** Single use: a valid code is removed on the way out. A code of the other
 *  type is refused and LEFT pending, so the device it was meant for can still
 *  use it. */
export function consommerCode(code: string, now = Date.now(), type: AppareilType = 'atelier'): CodeEnrolement | null {
  purgerCodes(now)
  const c = codes.get(code)
  if (!c || c.type !== type) return null
  codes.delete(code)
  return c
}

// ── Brute-force brake on the public enrolment endpoint ─────────────────────
// A million codes and a 10-minute window would take a determined LAN client
// seconds without this. Ten misses per client per window, then 429.

const MISS_MAX = 10
const MISS_WINDOW_MS = 15 * 60_000
const misses = new Map<string, { n: number; depuis: number }>()

/** True when this client may still try. `now` injectable for tests. */
export function peutEssayer(client: string, now = Date.now()): boolean {
  const m = misses.get(client)
  if (!m) return true
  if (now - m.depuis > MISS_WINDOW_MS) {
    misses.delete(client)
    return true
  }
  return m.n < MISS_MAX
}

export function noterEchec(client: string, now = Date.now()): void {
  const m = misses.get(client)
  if (!m || now - m.depuis > MISS_WINDOW_MS) misses.set(client, { n: 1, depuis: now })
  else m.n += 1
}

export function oublierEchecs(client: string): void {
  misses.delete(client)
}

// ── Enrol / revoke ─────────────────────────────────────────────────────────

/** Create the phone's row and return the cookie value to hand it. */
export async function enroler(
  c: CodeEnrolement,
  now = Date.now(),
): Promise<{ appareil: AppareilAtelier; token: string }> {
  const secret = crypto.randomBytes(32).toString('base64url')
  const appareil = await ecrire((f) => {
    const id = f.appareils.reduce((m, a) => Math.max(m, a.id), 0) + 1
    const row: AppareilAtelier = {
      id,
      type: c.type,
      secretHash: hashSecret(secret),
      IDutilisateur: c.IDutilisateur,
      IDbonnetier: c.IDbonnetier,
      libelle: c.libelle,
      creeLe: new Date(now).toISOString(),
      creePar: c.creePar,
      vuLe: new Date(now).toISOString(),
    }
    f.appareils.push(row)
    return row
  })
  return { appareil, token: `${appareil.id}.${secret}` }
}

export async function revoquer(id: number): Promise<boolean> {
  return ecrire((f) => {
    const before = f.appareils.length
    f.appareils = f.appareils.filter((a) => a.id !== id)
    return f.appareils.length !== before
  })
}

export async function renommer(id: number, libelle: string): Promise<AppareilPublic | null> {
  return ecrire((f) => {
    const row = f.appareils.find((a) => a.id === id)
    if (!row) return null
    row.libelle = libelle
    return publier(row)
  })
}
