// Compte client — the accounting account code stored in `client.compte`.
//
// Shape: the French chart-of-accounts customer prefix "411" followed by a short
// mnemonic derived from the customer name, e.g. "411THUA" (THUASNE),
// "411SLIP" (Le slip Francais). New codes generated by MPS_NG are always
// 411 + **3** alphanumerics.
//
// Legacy note (measured on the live table, 649 clients carry a compte):
//   411 + 4 chars → 388 rows   411 + 3 chars → 225 rows   other shapes → 36 rows
// So the stored data mixes 3- and 4-char suffixes. Generation standardises on 3
// (product decision), but VALIDATION accepts 3-or-more so that editing any of
// the 388 existing 4-char clients never gets blocked. Likewise uniqueness is
// only enforced on values that actually change — 10 duplicate codes already
// exist in the legacy data and must stay saveable.
//
// The generator is deterministic: same name + same taken-set → same code.

import { query } from './hfsql-auto.js'

export const COMPTE_PREFIX = '411'
/** Length of the suffix generated for a NEW client. */
export const COMPTE_SUFFIX_LEN = 3
/** Accepts generated (3) and legacy (4+) suffixes. */
export const COMPTE_RE = /^411[A-Z0-9]{3,}$/

const ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'

/** Legal forms and honorifics — never the mnemonic when a real word follows. */
const LEGAL_WORDS = new Set([
  'SOCIETE', 'STE', 'SARL', 'SAS', 'SASU', 'SA', 'SNC', 'SCI', 'SCP', 'SCA', 'SCAE',
  'SCOP', 'SELARL', 'SPRL', 'EURL', 'GIE', 'GROUPE', 'GROUP', 'HOLDING',
  'LTD', 'LIMITED', 'INC', 'CO', 'CORP', 'GMBH', 'AG', 'BV', 'NV', 'SPA', 'SRL', 'PLC', 'LLC',
  'ETS', 'ETABLISSEMENT', 'ETABLISSEMENTS',
  'ASSOCIATION', 'ASSOC', 'ASS', 'AMICALE',
  'MONSIEUR', 'MADAME', 'MADEMOISELLE', 'MR', 'MME', 'MLLE', 'M',
  'LA', 'LE', 'LES', 'L', 'UN', 'UNE', 'DE', 'DU', 'DES', 'D', 'ET', 'AU', 'AUX', 'THE', 'A',
])

/** Industry-generic words: legacy consistently skipped these too
 *  ("Bonneterie Gautier" → 411GAUT, "Transports SARL Lenglet…" → 411LENG). */
const GENERIC_WORDS = new Set([
  'BONNETERIE', 'BONNETTERIE', 'TRICOTAGE', 'MANUFACTURE', 'MAISON',
  'ATELIER', 'ATELIERS', 'TRANSPORT', 'TRANSPORTS', 'ENTREPRISE', 'FABRIQUE',
])

/** Strip diacritics, uppercase, keep A-Z/0-9 and single spaces. */
function fold(s: string): string {
  return (s ?? '')
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toUpperCase()
    .replace(/[^A-Z0-9]+/g, ' ')
    .trim()
}

/** Uppercase + drop everything that isn't alphanumeric. Cleans the dirty
 *  legacy values on the way through ("411 SEM" → "411SEM"). */
export function normalizeCompte(v: string | null | undefined): string {
  return (v ?? '')
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toUpperCase()
    .replace(/[^A-Z0-9]/g, '')
}

export function isValidCompte(v: string | null | undefined): boolean {
  return COMPTE_RE.test(normalizeCompte(v))
}

/** Significant words of a customer name, most meaningful first.
 *  Falls back to the raw word list when filtering would leave nothing. */
function significantWords(nom: string): string[] {
  const all = fold(nom).split(' ').filter((w) => w.length > 0)
  if (all.length === 0) return []
  const noLegal = all.filter((w) => !LEGAL_WORDS.has(w))
  const base = noLegal.length > 0 ? noLegal : all
  const noGeneric = base.filter((w) => !GENERIC_WORDS.has(w))
  return noGeneric.length > 0 ? noGeneric : base
}

/** Pad a partial mnemonic to exactly `COMPTE_SUFFIX_LEN` using the remaining
 *  letters of the name, then digits — so a 2-letter name still yields a code. */
function pad(partial: string, pool: string): string | null {
  let out = partial
  for (const ch of pool) {
    if (out.length >= COMPTE_SUFFIX_LEN) break
    out += ch
  }
  for (let d = 0; out.length < COMPTE_SUFFIX_LEN; d++) out += String(d % 10)
  out = out.slice(0, COMPTE_SUFFIX_LEN)
  return /^[A-Z0-9]{3}$/.test(out) ? out : null
}

/** Ordered mnemonic candidates for a name, best first. Every entry is exactly
 *  COMPTE_SUFFIX_LEN chars. Duplicates are removed, order preserved. */
export function compteSuffixCandidates(nom: string): string[] {
  const words = significantWords(nom)
  if (words.length === 0) return []
  const pool = words.join('')
  const [w1, w2 = '', w3 = ''] = words
  const consonants = w1.charAt(0) + w1.slice(1).replace(/[AEIOUY]/g, '')

  const raw = [
    w1.slice(0, 3),                              // THUASNE       → THU
    w1.slice(0, 2) + (w2.charAt(0) || ''),       // Le slip Franc → SLF (after stop-words)
    w1.charAt(0) + w2.slice(0, 2),               // …             → SFR
    w2.slice(0, 3),                              // second word
    consonants.slice(0, 3),                      // GAUTIER       → GTR
    w1.charAt(0) + w2.charAt(0) + w3.charAt(0),  // initials
    w3.slice(0, 3),                              // third word
    w1.slice(0, 2) + (w1.charAt(3) || ''),       // THUASNE       → THA
  ]

  const out: string[] = []
  const seen = new Set<string>()
  for (const r of raw) {
    const c = pad(r, pool)
    if (c && !seen.has(c)) { seen.add(c); out.push(c) }
  }
  // Numeric variants of the strongest mnemonic — "411SIG2" style, which legacy
  // itself used to separate SIGVARIS from SIGVARIS SAS.
  const stem2 = pad(w1.slice(0, 2), pool)?.slice(0, 2) ?? ''
  if (stem2.length === 2) {
    for (let d = 2; d <= 9; d++) {
      const c = stem2 + String(d)
      if (!seen.has(c)) { seen.add(c); out.push(c) }
    }
  }
  return out
}

/** First free code for `nom`, given the codes already in use (normalized,
 *  including the "411" prefix). Always returns a valid, unique compte. */
export function pickCompte(nom: string, taken: ReadonlySet<string>): string {
  for (const suffix of compteSuffixCandidates(nom)) {
    const c = COMPTE_PREFIX + suffix
    if (!taken.has(c)) return c
  }
  // Exhaustive deterministic sweep — 36^3 = 46 656 combinations, so this can
  // only fail if literally every code is taken (654 clients today).
  for (let i = 0; i < ALPHABET.length ** COMPTE_SUFFIX_LEN; i++) {
    let n = i
    let suffix = ''
    for (let p = 0; p < COMPTE_SUFFIX_LEN; p++) {
      suffix = ALPHABET[n % ALPHABET.length] + suffix
      n = Math.floor(n / ALPHABET.length)
    }
    const c = COMPTE_PREFIX + suffix
    if (!taken.has(c)) return c
  }
  throw new Error('compte_client: no free code left')
}

/** Every compte currently stored, normalized. `excludeId` drops one client's
 *  own code so re-saving it unchanged never collides with itself.
 *  Not scoped to IDsociete: the code identifies the company in the accounting
 *  ledger, so two different customers must never share one, whichever
 *  société they belong to. */
export async function loadTakenComptes(excludeId?: number): Promise<Set<string>> {
  const rows = await query<{ IDclient: unknown; compte: unknown }>(
    `SELECT IDclient, compte FROM client`,
  )
  const taken = new Set<string>()
  for (const r of rows) {
    if (excludeId !== undefined && Number(r.IDclient) === excludeId) continue
    const c = normalizeCompte(r.compte == null ? '' : String(r.compte))
    if (c) taken.add(c)
  }
  return taken
}

/** Generate a fresh, unique compte for `nom` (reads the table). */
export async function generateCompteClient(nom: string, excludeId?: number): Promise<string> {
  const taken = await loadTakenComptes(excludeId)
  return pickCompte(nom, taken)
}
