/**
 * PostgreSQL backend of the MPS API — step 3 of the HFSQL → PostgreSQL
 * migration (sibling repo windev_migration, docs/plan.md).
 *
 * Selected by `DB_BACKEND=pg` in hfsql-auto.ts. It exposes the SAME interface
 * as the HFSQL clients (query / queryRaw / queryB64Text / fixEncoding /
 * closeConnection / createClient) so the existing routes run unchanged:
 *
 *   1. translateSql() rewrites the few HFSQL-only constructs (TOP n,
 *      CONVERT(… USING …), x'hex' blobs, accented identifiers);
 *   2. the rows come back with the keys and value shapes the Linux bridge
 *      produces today, so the web apps receive byte-identical JSON:
 *        - keys: PostgreSQL folds every unquoted name to lowercase, HFSQL
 *          returns names as written in the query, and the table's own
 *          spelling for `SELECT *` (pg-keymap.json, generated by the nightly
 *          copy from the driver's header). restoreKeys() puts them back;
 *        - DATE → 'YYYYMMDD', TIMESTAMP → 'YYYY-MM-DD HH:MM:SS.mmm',
 *          bigint / numeric → number (all measured on the prod API host).
 *   3. fixEncoding is a no-op: PostgreSQL returns clean UTF-8.
 *
 * Verified route by route with the shadow diff (scripts/shadow-diff.ts),
 * which compares the same GET on the HFSQL API and on this backend.
 */
import postgres from 'postgres'
import { readFileSync } from 'fs'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'
import type { HfsqlClient } from './hfsql.js'

// ── Value shapes ─────────────────────────────────────────────

/** 'YYYY-MM-DD' → 'YYYYMMDD' (HFSQL date columns over the bridge). */
export function pgDateToHfsql(v: string): string {
  return v.replace(/-/g, '')
}

/** 'YYYY-MM-DD HH:MM:SS[.f]' → 'YYYY-MM-DD HH:MM:SS.mmm' (always 3 digits). */
export function pgTimestampToHfsql(v: string): string {
  const [head, frac = ''] = v.split('.')
  return `${head}.${(frac + '000').slice(0, 3)}`
}

// ── SQL translation ──────────────────────────────────────────

const unaccent = (s: string) => s.normalize('NFD').replace(/[̀-ͯ]/g, '')

/**
 * HFSQL's compact DATETIME literal — 'YYYYMMDDHHMMSS' — spelled the way
 * PostgreSQL reads it. The API writes that shape everywhere (nowDt() in
 * production-trm.ts, dtLiteral in planning-atelier.ts, pointage-etat.ts …);
 * PostgreSQL parses the 8-digit DATE form happily but rejects the 14-digit one
 * with « date/time field value out of range » — which took out /api/trs/atelier
 * and /api/trs/equipe entirely until the shadow diff surfaced it.
 *
 * Deliberately strict: exactly 14 digits AND a real calendar time. A lot number
 * or a barcode of 14 digits stays a string, because it would have to be a valid
 * date and time to be rewritten.
 */
export function hfsqlDateTimeLiteral(literal: string): string {
  const m = /^'(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})'$/.exec(literal)
  if (!m) return literal
  const [, y, mo, d, h, mi, s] = m
  const ok =
    +y >= 1900 && +y <= 2199 && +mo >= 1 && +mo <= 12 && +d >= 1 && +d <= 31 &&
    +h <= 23 && +mi <= 59 && +s <= 59
  return ok ? `'${y}-${mo}-${d} ${h}:${mi}:${s}'` : literal
}

interface Token { kind: 'str' | 'hex' | 'word' | 'other'; text: string }

/** Split SQL into string literals, x'hex' literals, words and the rest. */
export function tokenize(sql: string): Token[] {
  const out: Token[] = []
  let i = 0
  while (i < sql.length) {
    const c = sql[i]
    if ((c === 'x' || c === 'X') && sql[i + 1] === "'" && !/[\wÀ-ÿ]/.test(sql[i - 1] ?? '')) {
      const end = sql.indexOf("'", i + 2)
      out.push({ kind: 'hex', text: sql.slice(i, end + 1) })
      i = end + 1
    } else if (c === "'") {
      let j = i + 1
      while (j < sql.length) {
        if (sql[j] === "'" && sql[j + 1] === "'") j += 2
        else if (sql[j] === "'") break
        else j++
      }
      out.push({ kind: 'str', text: sql.slice(i, j + 1) })
      i = j + 1
    } else if (/[A-Za-z_À-ÿ]/.test(c)) {
      let j = i + 1
      while (j < sql.length && /[\wÀ-ÿ]/.test(sql[j])) j++
      out.push({ kind: 'word', text: sql.slice(i, j) })
      i = j
    } else {
      out.push({ kind: 'other', text: c })
      i++
    }
  }
  return out
}

/**
 * HFSQL SQL → PostgreSQL SQL. Only what the two dialects spell differently;
 * everything else (unquoted mixed-case names fold to our lowercase schema)
 * passes through. Throws on a construct it cannot translate, so a route
 * fails loudly in the shadow diff instead of returning something wrong.
 */
export function translateSql(sql: string): string {
  const toks = tokenize(sql)
  const out: string[] = []
  // Pending LIMITs: TOP n moves to the end of its own SELECT, i.e. before the
  // parenthesis closing the depth it was opened at (or the end of the text).
  const limits: { depth: number; n: string }[] = []
  // Open ORDER BY clauses, per parenthesis depth: `dir` = the current item
  // already carries ASC/DESC. HFSQL sorts NULL as the smallest value (first
  // ascending, last descending — measured on prod 2026-09-22, prospect.date);
  // PostgreSQL does the opposite, so every item gets its NULLS placement.
  const orderBy = new Map<number, { dir: boolean }>()
  const endItem = (d: number) => {
    const o = orderBy.get(d)
    if (o && !o.dir) out.push(' NULLS FIRST')
    if (o) o.dir = false
  }
  const endOrderBy = (d: number) => { endItem(d); orderBy.delete(d) }
  const nextWord = (k: number) => toks.slice(k + 1).find(x => x.kind !== 'other' || !/^\s$/.test(x.text))
  let depth = 0
  for (let k = 0; k < toks.length; k++) {
    const t = toks[k]
    if (t.kind === 'hex') {
      out.push(`'\\x${t.text.slice(2, -1)}'::bytea`)
      continue
    }
    if (t.kind === 'str') { out.push(hfsqlDateTimeLiteral(t.text)); continue }
    if (t.kind === 'other') {
      if (t.text === '(') depth++
      if (t.text === ',' && orderBy.has(depth)) endItem(depth)
      if (t.text === ')') {
        if (orderBy.has(depth)) endOrderBy(depth)
        const i = limits.findIndex(l => l.depth === depth)
        if (i >= 0) { out.push(` LIMIT ${limits[i].n}`); limits.splice(i, 1) }
        depth--
      }
      out.push(t.text)
      continue
    }
    const up = t.text.toUpperCase()
    if (up === 'ORDER' && nextWord(k)?.text.toUpperCase() === 'BY') {
      orderBy.set(depth, { dir: false })
    } else if ((up === 'ASC' || up === 'DESC') && orderBy.has(depth)) {
      out.push(t.text)
      if (nextWord(k)?.text.toUpperCase() !== 'NULLS') out.push(up === 'ASC' ? ' NULLS FIRST' : ' NULLS LAST')
      orderBy.get(depth)!.dir = true
      continue
    } else if (['LIMIT', 'OFFSET', 'FOR', 'UNION', 'FETCH', 'EXCEPT', 'INTERSECT'].includes(up) && orderBy.has(depth)) {
      // Trim the blank before the keyword so « NULLS FIRST » sits right after the item.
      const blank = out.length && /^\s$/.test(out[out.length - 1]) ? out.pop()! : ''
      endOrderBy(depth)
      out.push(blank)
    }
    if (up === 'TOP') {
      // SELECT [DISTINCT] TOP <n>
      let j = k + 1
      while (/^\s$/.test(toks[j]?.text ?? '')) j++
      let digits = ''
      while (/^\d$/.test(toks[j]?.text ?? '')) digits += toks[j++].text
      if (!digits) throw new Error(`pg-backend: TOP without a number in: ${sql.slice(0, 200)}`)
      limits.push({ depth, n: digits })
      // drop « TOP <n> » and the blank after it
      k = /^\s$/.test(toks[j]?.text ?? '') ? j : j - 1
      continue
    }
    if (up === 'CONVERT') {
      // CONVERT(expr USING 'enc') → (expr): PostgreSQL text is already UTF-8.
      let j = k + 1
      while (toks[j]?.text === ' ') j++
      if (toks[j]?.text === '(') {
        let d = 0, usingAt = -1, end = -1
        for (let m = j; m < toks.length; m++) {
          if (toks[m].text === '(') d++
          if (toks[m].text === ')') { d--; if (d === 0) { end = m; break } }
          if (d === 1 && toks[m].kind === 'word' && toks[m].text.toUpperCase() === 'USING') usingAt = m
        }
        if (end > 0 && usingAt > 0) {
          const inner = toks.slice(j + 1, usingAt).map(x => x.text).join('')
          out.push(`(${translateSql(inner).trim()})`)
          k = end
          continue
        }
      }
    }
    out.push(/[À-ÿ]/.test(t.text) ? unaccent(t.text) : t.text)
  }
  // End of text: close the ORDER BY items first, then the moved LIMITs.
  while (out.length && /^\s$/.test(out[out.length - 1])) out.pop()
  for (const d of [...orderBy.keys()].sort((a, b) => b - a)) endOrderBy(d)
  for (const l of limits.reverse()) out.push(` LIMIT ${l.n}`)
  return out.join('')
}

// ── Empty dates ──────────────────────────────────────────────

type DateCols = Record<string, { cols: string[]; dates: string[] }>

function loadJson<T>(name: string, fallback: T): T {
  try {
    const here = dirname(fileURLToPath(import.meta.url))
    return JSON.parse(readFileSync(join(here, name), 'utf8')) as T
  } catch {
    return fallback
  }
}

const DATECOLS: DateCols = loadJson('pg-datecols.json', {})

/** Tolerates a stale pg-datecols.json: an entry that is not { cols, dates } is
 *  ignored rather than crashing every write. */
const entryOf = (map: DateCols, schema: string, table: string) => {
  const e = map[`${schema}.${table.toLowerCase()}`] ?? map[`public.${table.toLowerCase()}`]
  return e && Array.isArray(e.cols) && Array.isArray(e.dates) ? e : undefined
}

const dateColsOf = (map: DateCols, schema: string, table: string): Set<string> =>
  new Set(entryOf(map, schema, table)?.dates ?? [])

/** Split a comma-separated SQL fragment at depth 0 (VALUES lists, SET lists). */
function splitTop(s: string): string[] {
  const out: string[] = []
  let depth = 0, start = 0, quote = false
  for (let i = 0; i < s.length; i++) {
    const c = s[i]
    if (quote) { if (c === "'") { if (s[i + 1] === "'") i++; else quote = false } ; continue }
    if (c === "'") quote = true
    else if (c === '(') depth++
    else if (c === ')') depth--
    else if (c === ',' && depth === 0) { out.push(s.slice(start, i)); start = i + 1 }
  }
  out.push(s.slice(start))
  return out
}

/**
 * HFSQL's empty date is the literal '' and the API writes it that way
 * (`date_notif = ''` when creating a commande-fil line, `date_relance = ''` on a
 * prospect, the archive stamp on a client). PostgreSQL answers « invalid input
 * syntax for type date: "" » and the whole write fails — three of the six write
 * scenarios died on it (windev_migration § B5, 2026-09-23).
 *
 * Only a column the copy reported as date / timestamp / time is touched
 * (pg-datecols.json, generated by the nightly run), so an empty string stays an
 * empty string everywhere else. Three shapes, which is all the API emits:
 *   UPDATE <t> SET <col> = ''            → SET <col> = NULL
 *   INSERT INTO <t> (<cols>) VALUES (…)  → the '' at a date column's position
 *   INSERT INTO <t> VALUES (…)           → by position, in the copy's own
 *                                          physical column order
 * The positional form is the accented-column pattern (setClientFlag in
 * clients-common.ts, prospects.ts), and it writes '' for a NULL date, so it
 * needs this as much as the named one.
 */
/** Replace '' with NULL at every date position of one VALUES tuple. `open` is
 *  the index of its opening parenthesis. */
function rewriteTuple(sql: string, open: number, names: string[], dates: Set<string>): string {
  let depth = 0, end = -1, quote = false
  for (let i = open; i < sql.length; i++) {
    const c = sql[i]
    if (quote) { if (c === "'") { if (sql[i + 1] === "'") i++; else quote = false } ; continue }
    if (c === "'") quote = true
    else if (c === '(') depth++
    else if (c === ')') { depth--; if (depth === 0) { end = i; break } }
  }
  if (end < 0) return sql
  const values = splitTop(sql.slice(open + 1, end))
  // A length mismatch means we are not reading the tuple we think we are: do nothing.
  if (values.length !== names.length) return sql
  const fixed = values.map((v, i) =>
    dates.has(names[i]) && /^\s*''\s*$/.test(v) ? v.replace("''", 'NULL') : v).join(',')
  return sql.slice(0, open + 1) + fixed + sql.slice(end)
}

export function emptyDatesToNull(sql: string, schema: string, map: DateCols = DATECOLS): string {
  const upd = /^\s*UPDATE\s+([A-Za-z_][\w]*)\s+SET\s/i.exec(sql)
  if (upd) {
    const dates = dateColsOf(map, schema, upd[1])
    if (!dates.size) return sql
    const setStart = upd[0].length
    const tail = sql.slice(setStart)
    // The SET list ends at WHERE; everything after it is untouched.
    const m = /\sWHERE\s/i.exec(tail)
    const setList = m ? tail.slice(0, m.index) : tail
    const rest = m ? tail.slice(m.index) : ''
    const fixed = splitTop(setList).map(item => {
      const a = /^(\s*)([A-Za-z_][\w]*)(\s*=\s*)''\s*$/.exec(item)
      return a && dates.has(a[2].toLowerCase()) ? `${a[1]}${a[2]}${a[3]}NULL` : item
    }).join(',')
    return sql.slice(0, setStart) + fixed + rest
  }

  const named = /^\s*INSERT\s+INTO\s+([A-Za-z_][\w]*)\s*\(([^)]*)\)\s*VALUES\s*\(/i.exec(sql)
  if (named) {
    const dates = dateColsOf(map, schema, named[1])
    if (!dates.size) return sql
    const names = splitTop(named[2]).map(s => s.trim().toLowerCase())
    if (!names.some(n => dates.has(n))) return sql
    return rewriteTuple(sql, named[0].length - 1, names, dates)
  }

  const positional = /^\s*INSERT\s+INTO\s+([A-Za-z_][\w]*)\s*VALUES\s*\(/i.exec(sql)
  if (positional) {
    const entry = entryOf(map, schema, positional[1])
    if (!entry?.dates.length) return sql
    return rewriteTuple(sql, positional[0].length - 1, entry.cols, new Set(entry.dates))
  }
  return sql
}

// ── Key restoration ──────────────────────────────────────────

type KeyMap = Record<string, Record<string, string>>

function loadKeymap(): KeyMap {
  try {
    const here = dirname(fileURLToPath(import.meta.url))
    return JSON.parse(readFileSync(join(here, 'pg-keymap.json'), 'utf8')) as KeyMap
  } catch {
    return {}
  }
}

const KEYMAP = loadKeymap()

/** Columns HFSQL hands back UPPERCASE whatever the query wrote (CLAUDE.md § HFSQL). */
const HFSQL_UPPERCASED = new Set(['date', 'type'])

/**
 * lowercase key → the key HFSQL would have returned for this query.
 * Priority: aliases (AS x) → names written in the query → the table's own
 * spelling (keymap, for `SELECT *`) → as is.
 */
export function keyResolver(sql: string, schema: string, keymap: KeyMap = KEYMAP): (k: string) => string {
  const toks = tokenize(sql).filter(t => t.kind === 'word')
  const aliases = new Map<string, string>()
  const written = new Map<string, string>()
  const tables: string[] = []
  for (let i = 0; i < toks.length; i++) {
    const w = unaccent(toks[i].text)
    const prev = toks[i - 1]?.text.toUpperCase()
    if (prev === 'AS') aliases.set(w.toLowerCase(), w)
    else if (!written.has(w.toLowerCase())) written.set(w.toLowerCase(), w)
    const qualified = keymap[`${schema}.${w.toLowerCase()}`] ?? keymap[`public.${w.toLowerCase()}`]
    if (qualified) tables.push(w.toLowerCase())
  }
  const selectStar = /\bSELECT\s+(DISTINCT\s+)?(TOP\s+\d+\s+)?(\w+\.)?\*/i.test(sql)
  const cache = new Map<string, string>()
  return (k: string) => {
    let r = cache.get(k)
    if (r !== undefined) return r
    r = aliases.get(k)
    if (r === undefined) {
      const fromTable = tables.map(t => (keymap[`${schema}.${t}`] ?? keymap[`public.${t}`])?.[k]).find(Boolean)
      if (HFSQL_UPPERCASED.has(k)) r = k.toUpperCase()
      else if (selectStar && fromTable) r = fromTable
      else r = written.get(k) ?? fromTable ?? k
    }
    cache.set(k, r)
    return r
  }
}

function restoreKeys<T>(rows: Record<string, unknown>[], sql: string, schema: string): T[] {
  if (rows.length === 0) return rows as T[]
  const keyOf = keyResolver(sql, schema)
  return rows.map(row => {
    const o: Record<string, unknown> = {}
    for (const [k, v] of Object.entries(row)) o[keyOf(k)] = v
    return o as T
  })
}

// ── Client ───────────────────────────────────────────────────

/** HFSQL database name → PostgreSQL schema (pg_migrate.py SOURCES). */
const SCHEMA_OF: Record<string, string> = { mps: 'public', pointage: 'pointage' }

function schemaFor(connectionString: string): string {
  const db = /Database\s*=\s*([^;]*)/i.exec(connectionString)?.[1]?.trim().toLowerCase() ?? 'mps'
  return SCHEMA_OF[db] ?? 'public'
}

export function createPgClient(connectionString: string = process.env.HFSQL_CONNECTION_STRING ?? ''): HfsqlClient {
  const schema = schemaFor(connectionString)
  let sql: postgres.Sql | null = null
  const db = () => {
    const url = process.env.PG_CONNECTION_STRING
    if (!url) throw new Error('DB_BACKEND=pg but PG_CONNECTION_STRING is not set')
    sql ??= postgres(url, {
      max: 5,
      idle_timeout: 60,
      connection: { search_path: schema === 'public' ? 'public' : `${schema},public`, application_name: 'mps-api' },
      types: {
        int8: { to: 20, from: [20], serialize: (x: number) => String(x), parse: (x: string) => Number(x) },
        numeric: { to: 1700, from: [1700], serialize: (x: number) => String(x), parse: (x: string) => Number(x) },
        date: { to: 1082, from: [1082], serialize: (x: string) => x, parse: pgDateToHfsql },
        timestamp: { to: 1114, from: [1114], serialize: (x: string) => x, parse: pgTimestampToHfsql },
      },
    })
    return sql
  }

  async function run(text: string): Promise<Record<string, unknown>[]> {
    const translated = emptyDatesToNull(translateSql(text), schema)
    const rows = await db().unsafe(translated)
    return rows as unknown as Record<string, unknown>[]
  }

  return {
    async query<T = Record<string, unknown>>(text: string): Promise<T[]> {
      return restoreKeys<T>(await run(text), text, schema)
    },
    async queryRaw(text: string) {
      return restoreKeys<Record<string, unknown>>(await run(text), text, schema)
    },
    async queryB64Text<T = Record<string, unknown>>(text: string): Promise<T[]> {
      return restoreKeys<T>(await run(text), text, schema)
    },
    async fixEncoding<T extends object>(rows: T[]): Promise<T[]> {
      return rows
    },
    async closeConnection() {
      if (sql) { await sql.end({ timeout: 5 }); sql = null }
    },
  }
}

const defaultClient = createPgClient()
export const query = defaultClient.query
export const queryRaw = defaultClient.queryRaw
export const queryB64Text = defaultClient.queryB64Text
export const fixEncoding = defaultClient.fixEncoding
export const closeConnection = defaultClient.closeConnection
